# 本地数据库路径
db_path: ./DB/SQL.db

# 表结构信息
TABLE: # 
  cargo: # 表名 
    info: 货物销售表,主要存储货物名称、净收益率、损失率、环比增长率、销售量、货物品类、货物仓库、销售负责人名字、销售部门、销售负责人联系方式
    field: # 字段信息
      cargo_id: 货物编号
      cargo_name: 货物名称
      year: 年份
      net_yield: 净收益率%
      loss_rate: 损失率%
      month_on_month_growth_rate: 环比增长率%
      sales_volume: 销售量
      cargo_price: 货物单价
      cargo_category: 货物品类
      source_cargo: 货物来源
      storage_warehouse: 货物仓库
      sales_person_name: 销售责任人名字
      sales_person_id: 销售负责人id
      sales_department: 销售部门
      sales_person_numbers: 销售负责人联系方式
  sales:
    info: 人员信息表,主要存储销售人员人名、入职时间、当前业绩、职位等级
    field:
      sales_person_id: 销售人员id
      sales_person_name: 人员名称
      sales_person_level: 人员等级
      sales_person_work_date: 入职时间
      sales_person_leader_id: 人员主管id
      sales_person_leader_name: 人员主管名字
      sales_person_number: 人员电话
      sales_person_achievement_year: 人员业绩年份
      sales_person_achievement: 人员业绩
      sales_person_department: 人员部门名称
      sales_person_department_id: 人员部门id
  cargo_info:
    info: 货物信息表,主要存储货物名称、货物来源地、购买价格、货物大类、货物品类、供应商名称和供应商负责人
    field:
      cargo_info_id: 货物信息id
      cargo_id: 货物id
      cargo_name: 货物名称
      origin_cargo: 货物产地
      cargo_purchase_price: 货物购买价
      cargo_type: 货物大类
      cargo_category: 货物品类
      cargo_supply_company: 供货公司
      cargo_num: 货物数量
      cargo_supply_aftermarket_person: 货物售后负责人
      cargo_supply_aftermarket_person_number: 货物售后负责人联系电话
      cargo_supply_market_person: 货物公司销售负责人
      cargo_supply_market_person_number: 货物公司负责人联系电话
  depart_list:
    info: 部门表,主要存储部门名称、部门职责、部门主管
    field:
      department_id: 部门id
      department_name: 部门名称
      department_duty: 部门职责
      department_lead_name: 部门负责人名字
      department_lead_name_id: 部门负责人id
      department_person_nums: 部门人数
  purchase_info:
    info: 购买信息表,主要存储购买公司名称、购买公司街道、购买负责人、购买货物名称和数量以及类型
    field:
      purchase_company_id: 货物购买方id
      purchase_company_name: 货物购买方名称
      purchase_company_address: 货物购买方地址
      purchase_company_person_name: 货物购买方负责人人名
      purchase_company_person_numbers: 货物购买方负责人联系方式
      purchase_company_person_level: 货物购买方负责人职位
      purchase_cargo_name_id: 购买货物id
      purchase_cargo_name: 购买货物名称
      purchase_cargo_nums: 购买货物数量
      purchase_cargo_type: 购买货物大类
      purchase_cargo_category: 购买货物品类
  supply_company:
    info: 供应商信息表,主要存储供应商名称、供应商地址、供应商货物名称、入供应商目录日期
    field:
      supply_company_id: 供货公司id
      supply_company_name: 供货公司名称
      supply_company_address: 供货公司地址
      supply_company_product_id: 供货公司货物id
      supply_company_product_name: 供货公司货物名称
      supply_company_date: 供货公司入名录时间
      



